#
###################################
# Site configuration
##################################
#

title: Jake Lew
email: lzh961@gmail.com
description: Jake Lew's blog, powered by Jekyll.
url: https://makejoyforX.github.io

#
##################################
# Jekyll configuration
#################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:        /blog/:year/:month/:day/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
    - jekyll-paginate

paginate: 5
paginate_path: '/blog/page:num'
